#! /bin/sh

data_folder="$HOME/.vimprove" 
data="$data_folder/data" 
tips="$data_folder/tips"
active_tips="$data_folder/activetips"
command="$data_folder/vimprove"


if [ -d $data_folder -o -f $data_folder ]; then
    echo "The file or folder $data_folder already exists. Overwrite it? (y/n)"
    read response
    if [ $response != 'y' -a $response != 'Y' ]; then
        echo "Okay, shutting down."
        exit
    fi
fi

echo "Installing stuff..."

rm -rf $HOME/.vimprove
mkdir $data_folder
cp ./tips $tips
cp ./data $data

let current_day=`date +%s`/86400
echo "last_day: $current_day" >> $data

num_tips=`grep num_tips $data | sed 's/[^[:space:]]* //'`

if [ ! -f $active_tips ]; then
    sed "/\[`expr $num_tips + 1`\]/,$ d" ./tips > $active_tips
fi
if [ ! -f $command ]; then
    cp ./vimprove $command
fi


echo "\n**** One more step to do! ****
Add these lines to your .bashrc or .bash_profile:
     alias vimprove=\"~/.vimprove/vimprove\"
     vimprove

Great!
Check out usage info at https://www.github.com/ChrisPenner/vimprove
Each day it'll show you new vim tips!
As tips get older (and you master them) they disappear.
Run 'vimprove help' to learn more!
New tips will (hopefully) be added to the project all the time, so from time to
time just reclone and replace `~/.vimprove/tips` with the new `tips` file."
