#! /bin/sh

data_folder="$HOME/.vimtips" 
data="$data_folder/data" 
tips="$data_folder/tips"
active_tips="$data_folder/activetips"
command="$data_folder/vimtips"

rm -r $HOME/.vimtips
mkdir $data_folder
cp ./tips $tips
cp ./data $data

num_tips=`grep num_tips $data | sed 's/[^[:space:]]* //'`

if [ ! -f $active_tips ]; then
    head -n "$num_tips" ./tips > $active_tips
fi
if [ ! -f $command ]; then
    cp ./vimtips $command
fi


echo ">>> * One more step to do! *
Add these lines to your .bashrc or .bash_profile:
    \$HOME/.vimtips/vimtips
    alias vimtips="$HOME/.vimtips/vimtips"

>>> Great!
>>> Each day it'll show you new vim tips!
>>> As tips get older (and you master them) they disappear.
>>> Right now it's configured to show the most recent $num_tips tips,
>>> change this with 'vimtips numtips <num>'"
