#! /bin/sh
# Find current day as integer
let current_day=`date +%s`/86400
data_folder="$HOME/.vimtips" 
data="$data_folder/data" 
temp="$data_folder/temp"
temp2="$data_folder/temp2"
tips="$data_folder/tips"
active_tips="$data_folder/activetips"

# Get values
last_day=`grep last_day $data | sed 's/[^[:space:]]* //'`
current_tip=`grep current_tip $data | sed 's/[^[:space:]]* //'`
day_delta=`expr $current_day - $last_day`
num_tips=`grep num_tips $data | sed 's/[^[:space:]]* //'`
hide=`grep hide $data | sed 's/[^[:space:]]* //'`

case "$1" in
    'hide')
        # Set 'hide' option
        sed -i '' "s/hide.*/hide: true/" $data
        echo "Consider it done."
        exit
        ;;

    'show')
        sed -i '' "s/hide.*/hide: false/" $data
        echo "Consider it done."
        exit
        ;;

    'clear')
        shift
        # Wipe everything except commas and spaces (delimiters)
        num=`sed 's/[^[:digit:][:space:],]//g' <<< "$@"`

        # Change commas and spaces to newlines
        num=`tr -s ' ,' '\n' <<< "$num"`
        for n in $num; do
            sed -i "/\[$n\]/,/\[/ {/^ / d;}" tips
            sed -i "/\[$n\]/ d" tips
            echo "[$n] Cleared!"
        done
        exit
        ;;

    'add')
        shift
        # Wipe everything except commas and spaces (delimiters)
        num=`sed 's/[^[:digit:][:space:],]//g' <<< "$@"`

        # Change commas and spaces to newlines
        num=`tr -s ' ,' '\n' <<< "$num"`

        for n in $num; do
            # Add item to active tips ONLY if it's not already there.
            if [ ! "`grep "\[$n\]" $active_tips`" ]; then
                sed -n "/\[$n\]/ p" $tips >> $active_tips
                sed -n "/\[$n\]/,/\[/ {/^ /p;}" $tips >> $active_tips
            fi
        done
        ;;

    'numtips')
        shift
        # Wipe everything except numbers and spaces
        numtips=`tr -c -s '[0-9]' ' ' <<<"$@"`
        # Only use first number
        echo "$num" | read numtips rest
        # Update setting
        sed -i '' "s/num_tips.*/num_tips: $numtips/" $data
        echo "Now showing max $numtips tips"
        exit
        ;;

    'next')
        current_tip=`expr $current_tip + 1`

        # Update current item.
        sed -i '' "s/current_tip.*/current_tip: $current_tip/" $data

        # Add current item to active tips ONLY if it's not already there.
        if [ ! "`grep "\[$current_tip\]" $active_tips`" ]; then
            # grep "\[$current_tip\]" $tips >> $active_tips
            sed -n "/\[$current_tip\]/ p" $tips >> $active_tips
            sed -n "/\[$current_tip\]/,/\[/ {/^ /p;}" $tips >> $active_tips
        fi
        ;;

    *)
        if [ ! $1 ]; then
            if [ ! $hide = 'true' ]; then
                echo "== Vimtips == ('vimtips help' for help)"
            fi
        else
            echo "usage:
            'vimtips next' - adds new tip
            'vimtips clear <x> <y> <z>...' clears tip numbers x, y, and z from list
            'vimtips numtips <n>' shows only <n> tips from now on."
            exit
        fi
        ;;

    esac

    if [ $day_delta -gt 0 ]; then
        current_tip=`expr $current_tip + 1`

        # Update current item.
        sed -i '' "s/current_tip.*/current_tip: $current_tip/" $data

        # Add current item to active tips ONLY if it's not already there.
        if [ ! "`grep "\[$current_tip\]" $active_tips`" ]; then
            # grep "\[$current_tip\]" $tips >> $active_tips
            sed -n "/\[$current_tip\]/ p" $tips >> $active_tips
            sed -n "/\[$current_tip\]/,/\[/ {/^ /p;}" $tips >> $active_tips
        fi
    fi

    # Update last_day
    sed -i '' "s/last_day.*/last_day: $current_day/" $data

    echo '' > $temp
    echo '' > $temp2
    # Remove tips until under limit
    while [ `grep '\[.*\]' $active_tips | wc -l` -ge $num_tips ]; do
        head -n 1 $active_tips > $temp
        tail -n +2 $active_tips > $temp2
        cat $temp2 > $active_tips
    done
    cat $active_tips >> $temp
    cat $temp | sed '/^$/d' > $active_tips
    rm -f "$data_folder/temp*"

    cat $active_tips
